### ISSUE TITLE
Branches in the environment list are barely visible

### ISSUE THREAD

**Issue by dasJ** [vednoc/dark-gitlab#1]
From https://git.example.com/$org/$project/-/environments:

![image](https://user-images.githubusercontent.com/4971975/88467024-759a8d00-ceca-11ea-97d2-f337d8d009a6.png)

Meanwhile it looks great in my pipelines:

![image](https://user-images.githubusercontent.com/4971975/88467071-dfb33200-ceca-11ea-8b63-f880471e67ac.png)

**Comment by vednoc** [comment]
I don't actually have an access to a page like that. Could you copy HTML for the entire table? If so, be sure to remove sensitive information.

**Comment by dasJ** [comment]
Is the css selector enough?

`html body.ui-dark.tab-width-4.gl-browser-firefox.gl-platform-linux div.layout-page.page-with-contextual-sidebar div.content-wrapper div.container-fluid div#content-body.content div div.environments-container div.table-holder div.ci-table div.gl-responsive-table-row div.table-section.section-20 div.js-commit-component.table-mobile-content div.branch-commit.cgray a.gl-link.ref-name`

Current styles (probably enough, the color is there):
![image](https://user-images.githubusercontent.com/4971975/88467829-1d1bbd80-ced3-11ea-8ac2-7bc8ca895037.png)

**Comment by vednoc** [comment]
In this case it should be. Open DevTools, switch to Style Editor tab, press the `+` button and paste this line:

```css
.ci-table .ref-name { color: var(--light) !important }
```

If it fixes the issue, I'll push changes in the next update.

**Comment by dasJ** [comment]
Yes, it looks perfect with that extra rule. Thank you so much!
